"""add is_active to products

Revision ID: b1be9a41f41e
Revises: bbac4fff07de
Create Date: 2025-11-01 03:37:54.869127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1be9a41f41e'
down_revision: Union[str, None] = 'bbac4fff07de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_active column to products (use Boolean / tinyint for MySQL)
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.alter_column('categories', 'category_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('products', 'product_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('products', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('rewards', 'reward_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('rewards', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('rewards', 'source_txn_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('shopkeepers', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sync_logs', 'sync_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sync_logs', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('transactions', 'shop_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('transactions', 'product_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove is_active column on downgrade
    op.drop_column('products', 'is_active')
    op.alter_column('transactions', 'product_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sync_logs', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sync_logs', 'sync_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('shopkeepers', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('rewards', 'source_txn_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('rewards', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('rewards', 'reward_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('products', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('products', 'product_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'shop_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'category_id',
               existing_type=sa.UUID(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
